name: utammys_mobile_app
description: A mobile app to sell uniforms - clothing catalog with Laravel API integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/categorias/
    - assets/images/colegios/
    - assets/images/products/
    - assets/images/products/la_preparatoria/
    - assets/images/products/interamericano/
    - assets/images/products/metropolitano/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/utamys_white_bg.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/utamys_white_bg.png"

flutter_native_splash:
  color: "#0000FF"
  image: assets/images/utamys_white_bg.png
  android_12:
    image: assets/images/utamys_white_bg.png
    icon_background_color: "#FFFFFF"
  web: false
